#!/bin/bash

ACCESS_KEY=$AWS_ACCESS_KEY_ID
SECRET_KEY=$AWS_SECRET_ACCESS_KEY
REGION="us-west-1"
CLUSTER=""
SERVICE_NAME=""
COMPOSE_FILE=""

show_help () {
       	echo "Usage:"
       	echo "    -a ACCESS_KEY"
       	echo "    -s SECRET_ACCESS_KEY"
       	echo "    -c CLUSTER"
       	echo "    -n SERVICE_NAME"
       	echo "    -f DOCKER_COMPOSE_FILE"
       	echo "Example:"
       	echo "    $ deploy_to_ecs -c qa -n alert -f /alert-service/docker-compose-qa.yml"
       	echo ""
}

while getopts "h?a:s:c:n:f:" opt; do
    case "$opt" in
    h|\?)
        show_help
        exit 0
        ;;
    a)  ACCESS_KEY=$OPTARG
       	;;
    s)  SECRET_KEY=$OPTARG
       	;;
    c)  CLUSTER=$OPTARG
       	;;
    n)  SERVICE_NAME=$OPTARG
        ;;
    f)  COMPOSE_FILE=$OPTARG
        ;;
    esac
done

if [[ (-z "${ACCESS_KEY}") || (-z "${SECRET_KEY}") || (-z "${CLUSTER}") || (-z "${SERVICE_NAME}") || (-z "${COMPOSE_FILE}") ]]; then
       	echo "Missing arguments!"
       	echo ""
       	show_help
       	exit -1
fi

SERVICE_NAME=`echo $SERVICE_NAME | sed "s/[ _\-]//g"`

rm $HOME/.ecs/config

ecs-cli configure \
       	--access-key $ACCESS_KEY \
       	--secret-key $SECRET_KEY \
       	--region $REGION \
       	--cluster $CLUSTER \
       	--compose-project-name-prefix "" \
       	--compose-service-name-prefix ""

echo "--------------------------------------------------------------------------------"

ecs-cli compose --debug -p "$SERVICE_NAME" -f $COMPOSE_FILE service down

echo "--------------------------------------------------------------------------------"

SUCCESS=false

for i in {1..10}
do
	ecs-cli compose --debug -p "$SERVICE_NAME" -f $COMPOSE_FILE service up && $SUCCESS=true && break || echo "service up failed. Will retry after 10 seconds..." && sleep 10;
done

if [ "$SUCCESS" = true ] ; then
	echo "Could NOT deploy service..."
	exit -1
fi

